language: php
php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - composer install --dev

script:
    - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
    - php vendor/bin/coveralls -v
